# Generated by Django 3.2 on 2022-02-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapi', '0003_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='calendar',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='customapi.calendar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='interval',
            field=models.IntegerField(choices=[(15, '15'), (30, '30'), (45, '45')], default=15),
        ),
    ]
